# Generated by Django 3.1.1 on 2020-10-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200926_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'venda', 'verbose_name_plural': 'vendas'},
        ),
    ]
