openapi: 3.0.2
info:
  title: 'Events API'
  version: '1.0.0'
paths:
  /api/events/:
    post:
      operationId: createEvent
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
          description: ''
      tags:
      - api
  /api/events/{id}/cancel_occurrences/:
    post:
      operationId: cancelOccurrencesEvent
      description: 'Cancel event occurrences after after_dt datetime. If after_dt is not provided, cancel all present and future occurrences.'
      parameters:
      - name: id
        in: path
        required: true
        description: 'The event id.'
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                after_dt:
                  required: false
                  type: string
                  format: date-time
                  description: 'Datetime filter for occurrences starting after after_dt.'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
          description: ''
      tags:
      - api
  /api/events/{id}/:
    put:
      operationId: updateEvent
      description: 'Update event data.'
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateEvent
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyEvent
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
          readOnly: true
          description: ''
        tzoffset:
          type: integer
      required:
      - title
      - start
